RS_CAPTION_WARNING = 'Warning';
RS_CREATED_SUCCESSFULLY = 'The gocryptfs filesystem has been created successfully';

RS_DIRECTORY_EXISTS = 'Directory already exists';
RS_PASSWORDS_DO_NOT_MATCH = 'Passwords do not match';

RS_DIRECTORY_NOT_EXISTS = 'Directory not exists';
RS_ERROR_CREATING_DIRECTORY = 'Error creating the directory';
RS_ERROR_DEL_DIRECTORY = 'Error deleting the directory';
RS_ERROR_LOAD_CONFIG = 'Error load config';
RS_ERROR_RUN_EXECUTABLE = 'failed to run';
RS_ERROR_WRONG_PASSWORD = 'Error, something went wrong reading the password';
RS_ERR_SAVE_KEY = 'Error when saving key';
RS_FAILED_TO_RETRIEVE_RECOVERY_KEY = 'Vault was successfully created, but could not retrieve the recovery key';
RS_FAILED_TO_SAVE_LOG_FILE = 'Failed to save log file';
RS_PASSWORD_EMPTY = 'Password Empty';
RS_PASSWORD_INCORRECT = 'Password Incorrect';
RS_BIN_NOT_INSTALLED = 'Maybe %s is not installed';
RS_GOCRYPTFS_XRAY_FAILED_RUN_HINT = 'This is not critical, but you will not be able to get the master key when you create a new vault';

RS_FSCK_NO_PROBLEMS_FOUND = 'fsck summary: no problems found';
RS_KEY_SAVED = 'Key successfully saved';
RS_LOCK_ALL_AND_CLOSE = 'Lock all and close?';
RS_MOUNTPOINT_HINT = 'During the mount, directories with the storage name will be temporarily created in this directory, for example:';
RS_PLEASE_WAIT_UNTIL_THE_PROCESS = 'Please wait until the process is completed it may take some time ...';
RS_SUCCESSFULLY_MOUNTED = 'Filesystem mounted and ready';
RS_UNMOUNTED_SUCCESSFULLY = 'Unmounted successfully';
RS_VAULTPATH_HINT = 'Open in File Manager ...';

